import {
  Add01Icon,
  Alert01Icon,
  AlertCircleIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Award01Icon,
  Cancel01Icon,
  Cash02Icon,
  CustomerService01Icon,
  Delete02Icon,
  DeliveryReturn01Icon,
  DeliveryTruck01Icon,
  Edit02Icon,
  FavouriteIcon,
  FlashIcon,
  FolderOpenIcon,
  Image01Icon,
  ImageNotFound01Icon,
  InformationCircleIcon,
  Link01Icon,
  Location01Icon,
  MessageMultiple02Icon,
  Notification01Icon,
  PackageRemoveIcon,
  PencilEdit01Icon,
  AddCircleIcon,
  RemoveCircleIcon,
  Remove01Icon,
  Search01Icon,
  Share08Icon,
  ShieldBlockchainIcon,
  ShoppingBag01Icon,
  ShoppingBasket02Icon,
  StarHalfIcon,
  StarIcon,
  Store01Icon,
  Store02Icon,
  Tick01Icon,
  Tick02Icon,
  Coupon02Icon,
  UserIcon,
  ViewIcon,
  ViewOffIcon,
  Wallet02Icon,
  VideoCameraAiIcon
} from "@hugeicons/core-free-icons";

export const iconRegistry = {
  // Select icons
  Check: Tick02Icon,
  ChevronDown: ArrowDown01Icon,
  ChevronUp: ArrowUp01Icon,
  ChevronRight: ArrowRight01Icon,
  ChevronLeft: ArrowLeft01Icon,
  // Dialog icons
  X: Cancel01Icon,
  // Input icons
  Eye: ViewIcon,
  EyeOff: ViewOffIcon,
  // Dynamic usage icons
  Store: Store01Icon,
  Search: Search01Icon,
  FolderOpen: FolderOpenIcon,
  AlertCircle: AlertCircleIcon,
  // ProductCard icons
  Heart: FavouriteIcon,
  Add: Add01Icon,
  Remove: Remove01Icon,
  PackageRemove: PackageRemoveIcon,
  // Product detail page icons
  Star: StarIcon,
  StarHalf: StarHalfIcon,
  Share: Share08Icon,
  Cart: ShoppingBag01Icon,
  Flash: FlashIcon,
  Link: Link01Icon,
  Award: Award01Icon,
  Location: Location01Icon,
  CheckCircle: Tick01Icon,
  Truck: DeliveryTruck01Icon,
  DeliveryReturn: DeliveryReturn01Icon,
  Cash: Cash02Icon,
  ShieldBlockchain: ShieldBlockchainIcon,
  ImageNotFound: ImageNotFound01Icon,
  // Header navigation icons
  ShoppingCart: ShoppingBasket02Icon,
  User: UserIcon,
  // Account sidebar icons
  Wallet: Wallet02Icon,
  Edit: Edit02Icon,
  Pencil: PencilEdit01Icon,
  Bell: Notification01Icon,
  Studio: Store02Icon,
  Coupon: Coupon02Icon,
  Support: CustomerService01Icon,
  Feedback: MessageMultiple02Icon,
  // Toast icons
  Info: InformationCircleIcon,
  Warning: Alert01Icon,
  // Wishlist icons
  Image: Image01Icon,
  AddCircle: AddCircleIcon,
  RemoveCircle: RemoveCircleIcon,
  Trash: Delete02Icon,
  VideoCameraSpark: VideoCameraAiIcon
} as const;


export type IconName = keyof typeof iconRegistry;
