import {
  Add01Icon,
  Alert01Icon,
  AlertCircleIcon,
  ArrowDown01Icon,
  Coins01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Award01Icon,
  Briefcase01Icon,
  Cancel01Icon,
  Cash02Icon,
  ChartUpIcon,
  CustomerService01Icon,
  Delete02Icon,
  DeliveryDelay01Icon,
  Calendar03Icon,
  DeliveryReturn01Icon,
  DeliverySent01Icon,
  DeliveryTracking01Icon,
  DeliveryTruck01Icon,
  Package01Icon,
  PackageAdd01Icon,
  Package03Icon,
  PackageDelivered01Icon,
  PackageOpenIcon,
  Edit02Icon,
  FavouriteIcon,
  FlashIcon,
  FolderOpenIcon,
  Home01Icon,
  Image01Icon,
  ImageNotFound01Icon,
  ImageUpload01Icon,
  Link01Icon,
  Location01Icon,
  MessageMultiple02Icon,
  MoreVerticalIcon,
  Notification01Icon,
  PackageRemoveIcon,
  PencilEdit01Icon,
  AddCircleIcon,
  RemoveCircleIcon,
  Remove01Icon,
  Search01Icon,
  Share08Icon,
  ShieldBlockchainIcon,
  ShoppingBag01Icon,
  ShoppingBasket02Icon,
  StarHalfIcon,
  StarIcon,
  Store01Icon,
  Store02Icon,
  InformationCircleFreeIcons,
  Tick01Icon,
  Tick02Icon,
  Coupon02Icon,
  CreditCardIcon,
  UserIcon,
  ViewIcon,
  ViewOffIcon,
  Wallet02Icon,
  VideoCameraAiIcon,
} from "@hugeicons/core-free-icons";

export const iconRegistry = {
  // Select icons
  Check: Tick02Icon,
  ChevronDown: ArrowDown01Icon,
  ChevronUp: ArrowUp01Icon,
  ChevronRight: ArrowRight01Icon,
  ChevronLeft: ArrowLeft01Icon,
  CreditCard: CreditCardIcon,
  // Dialog icons
  X: Cancel01Icon,
  // Input icons
  Eye: ViewIcon,
  EyeOff: ViewOffIcon,
  // Dynamic usage icons
  Store: Store01Icon,
  Search: Search01Icon,
  FolderOpen: FolderOpenIcon,
  AlertCircle: AlertCircleIcon,
  Info: InformationCircleFreeIcons,
  // ProductCard icons
  Heart: FavouriteIcon,
  Add: Add01Icon,
  Remove: Remove01Icon,
  PackageRemove: PackageRemoveIcon,
  // Product detail page icons
  Star: StarIcon,
  StarHalf: StarHalfIcon,
  Share: Share08Icon,
  Cart: ShoppingBag01Icon,
  Flash: FlashIcon,
  Link: Link01Icon,
  Award: Award01Icon,
  Location: Location01Icon,
  CheckCircle: Tick01Icon,
  Truck: DeliveryTruck01Icon,
  DeliveryReturn: DeliveryReturn01Icon,
  // Order status icons
  Package: Package01Icon,
  PackageAdd: PackageAdd01Icon,
  PackagePacked: Package03Icon,
  DeliverySent: DeliverySent01Icon,
  DeliveryTracking: DeliveryTracking01Icon,
  PackageDelivered: PackageDelivered01Icon,
  DeliveryDelay: DeliveryDelay01Icon,
  PackageOpen: PackageOpenIcon,
  Cash: Cash02Icon,
  ShieldBlockchain: ShieldBlockchainIcon,
  Calendar: Calendar03Icon,
  ImageNotFound: ImageNotFound01Icon,
  // Header navigation icons
  ShoppingCart: ShoppingBasket02Icon,
  User: UserIcon,
  // Account sidebar icons
  Wallet: Wallet02Icon,
  Edit: Edit02Icon,
  Pencil: PencilEdit01Icon,
  Bell: Notification01Icon,
  Studio: Store02Icon,
  Coupon: Coupon02Icon,
  Support: CustomerService01Icon,
  Feedback: MessageMultiple02Icon,
  // Toast icons
  Warning: Alert01Icon,
  // Wishlist icons
  Image: Image01Icon,
  AddCircle: AddCircleIcon,
  RemoveCircle: RemoveCircleIcon,
  Trash: Delete02Icon,
  VideoCameraSpark: VideoCameraAiIcon,
  // Review icons
  ImageUpload: ImageUpload01Icon,
  // Search icons
  TrendingUp: ChartUpIcon,
  // Cart icons
  Coins: Coins01Icon,
  // Address icons
  Home: Home01Icon,
  Briefcase: Briefcase01Icon,
  MoreVertical: MoreVerticalIcon,
} as const;

export type IconName = keyof typeof iconRegistry;
