/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedCategoriesIndexRouteImport } from './routes/_protected/categories/index'
import { Route as ProtectedCategoriesCategoryIdRouteImport } from './routes/_protected/categories/$categoryId'
import { Route as ProtectedProductProductProductIdRouteImport } from './routes/_protected/product/product.$productId'
import { Route as ProtectedCategoriesCategoryIdProductsRouteImport } from './routes/_protected/categories/$categoryId.products'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/_auth/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCategoriesIndexRoute =
  ProtectedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCategoriesCategoryIdRoute =
  ProtectedCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedProductProductProductIdRoute =
  ProtectedProductProductProductIdRouteImport.update({
    id: '/product/product/$productId',
    path: '/product/product/$productId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCategoriesCategoryIdProductsRoute =
  ProtectedCategoriesCategoryIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => ProtectedCategoriesCategoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/categories/$categoryId': typeof ProtectedCategoriesCategoryIdRouteWithChildren
  '/categories/': typeof ProtectedCategoriesIndexRoute
  '/categories/$categoryId/products': typeof ProtectedCategoriesCategoryIdProductsRoute
  '/product/product/$productId': typeof ProtectedProductProductProductIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/': typeof ProtectedIndexRoute
  '/categories/$categoryId': typeof ProtectedCategoriesCategoryIdRouteWithChildren
  '/categories': typeof ProtectedCategoriesIndexRoute
  '/categories/$categoryId/products': typeof ProtectedCategoriesCategoryIdProductsRoute
  '/product/product/$productId': typeof ProtectedProductProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/categories/$categoryId': typeof ProtectedCategoriesCategoryIdRouteWithChildren
  '/_protected/categories/': typeof ProtectedCategoriesIndexRoute
  '/_protected/categories/$categoryId/products': typeof ProtectedCategoriesCategoryIdProductsRoute
  '/_protected/product/product/$productId': typeof ProtectedProductProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify-otp'
    | '/categories/$categoryId'
    | '/categories/'
    | '/categories/$categoryId/products'
    | '/product/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verify-otp'
    | '/'
    | '/categories/$categoryId'
    | '/categories'
    | '/categories/$categoryId/products'
    | '/product/product/$productId'
  id:
    | '__root__'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/verify-otp'
    | '/_protected/'
    | '/_protected/categories/$categoryId'
    | '/_protected/categories/'
    | '/_protected/categories/$categoryId/products'
    | '/_protected/product/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/categories/': {
      id: '/_protected/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof ProtectedCategoriesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/categories/$categoryId': {
      id: '/_protected/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof ProtectedCategoriesCategoryIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/product/product/$productId': {
      id: '/_protected/product/product/$productId'
      path: '/product/product/$productId'
      fullPath: '/product/product/$productId'
      preLoaderRoute: typeof ProtectedProductProductProductIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/categories/$categoryId/products': {
      id: '/_protected/categories/$categoryId/products'
      path: '/products'
      fullPath: '/categories/$categoryId/products'
      preLoaderRoute: typeof ProtectedCategoriesCategoryIdProductsRouteImport
      parentRoute: typeof ProtectedCategoriesCategoryIdRoute
    }
  }
}

interface ProtectedCategoriesCategoryIdRouteChildren {
  ProtectedCategoriesCategoryIdProductsRoute: typeof ProtectedCategoriesCategoryIdProductsRoute
}

const ProtectedCategoriesCategoryIdRouteChildren: ProtectedCategoriesCategoryIdRouteChildren =
  {
    ProtectedCategoriesCategoryIdProductsRoute:
      ProtectedCategoriesCategoryIdProductsRoute,
  }

const ProtectedCategoriesCategoryIdRouteWithChildren =
  ProtectedCategoriesCategoryIdRoute._addFileChildren(
    ProtectedCategoriesCategoryIdRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedCategoriesCategoryIdRoute: typeof ProtectedCategoriesCategoryIdRouteWithChildren
  ProtectedCategoriesIndexRoute: typeof ProtectedCategoriesIndexRoute
  ProtectedProductProductProductIdRoute: typeof ProtectedProductProductProductIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedCategoriesCategoryIdRoute:
    ProtectedCategoriesCategoryIdRouteWithChildren,
  ProtectedCategoriesIndexRoute: ProtectedCategoriesIndexRoute,
  ProtectedProductProductProductIdRoute: ProtectedProductProductProductIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
