/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicCartRouteImport } from './routes/_public/cart'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as PublicSpotlightRouteRouteImport } from './routes/_public/spotlight/route'
import { Route as ProtectedAccountRouteRouteImport } from './routes/_protected/account/route'
import { Route as PublicSpotlightIndexRouteImport } from './routes/_public/spotlight/index'
import { Route as PublicCategoriesIndexRouteImport } from './routes/_public/categories/index'
import { Route as ProtectedAccountIndexRouteImport } from './routes/_protected/account/index'
import { Route as PublicSpotlightCampaignsRouteImport } from './routes/_public/spotlight/campaigns'
import { Route as PublicSpotlightBuyClipsRouteImport } from './routes/_public/spotlight/buy-clips'
import { Route as PublicProductProductIdRouteImport } from './routes/_public/product/$productId'
import { Route as PublicCategoriesCategoryIdRouteImport } from './routes/_public/categories/$categoryId'
import { Route as ProtectedAccountWalletRouteImport } from './routes/_protected/account/wallet'
import { Route as ProtectedAccountMyAddressRouteImport } from './routes/_protected/account/my-address'
import { Route as PublicSpotlightProtectedRouteRouteImport } from './routes/_public/spotlight/_protected/route'
import { Route as ProtectedAccountWishlistIndexRouteImport } from './routes/_protected/account/wishlist/index'
import { Route as ProtectedAccountMyOrdersIndexRouteImport } from './routes/_protected/account/my-orders/index'
import { Route as PublicSpotlightShortsIdRouteImport } from './routes/_public/spotlight/shorts.$id'
import { Route as PublicSpotlightProtectedMyPostsRouteImport } from './routes/_public/spotlight/_protected/my-posts'
import { Route as PublicSpotlightProtectedEditProfileRouteImport } from './routes/_public/spotlight/_protected/edit-profile'
import { Route as PublicSpotlightProtectedBookmarksRouteImport } from './routes/_public/spotlight/_protected/bookmarks'
import { Route as PublicSpotlightProtectedAnalyticsRouteImport } from './routes/_public/spotlight/_protected/analytics'
import { Route as PublicCategoriesProductsCategoryIdRouteImport } from './routes/_public/categories/products.$categoryId'
import { Route as ProtectedAccountWishlistCollectionIdRouteImport } from './routes/_protected/account/wishlist/$collectionId'
import { Route as ProtectedAccountMyOrdersOrderItemIdRouteImport } from './routes/_protected/account/my-orders/$orderItemId'
import { Route as ProtectedAccountMyOrdersReturnOrderItemIdRouteImport } from './routes/_protected/account/my-orders/return.$orderItemId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicSpotlightRouteRoute = PublicSpotlightRouteRouteImport.update({
  id: '/spotlight',
  path: '/spotlight',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedAccountRouteRoute = ProtectedAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicSpotlightIndexRoute = PublicSpotlightIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSpotlightRouteRoute,
} as any)
const PublicCategoriesIndexRoute = PublicCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedAccountIndexRoute = ProtectedAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAccountRouteRoute,
} as any)
const PublicSpotlightCampaignsRoute =
  PublicSpotlightCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => PublicSpotlightRouteRoute,
  } as any)
const PublicSpotlightBuyClipsRoute = PublicSpotlightBuyClipsRouteImport.update({
  id: '/buy-clips',
  path: '/buy-clips',
  getParentRoute: () => PublicSpotlightRouteRoute,
} as any)
const PublicProductProductIdRoute = PublicProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCategoriesCategoryIdRoute =
  PublicCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const ProtectedAccountWalletRoute = ProtectedAccountWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ProtectedAccountRouteRoute,
} as any)
const ProtectedAccountMyAddressRoute =
  ProtectedAccountMyAddressRouteImport.update({
    id: '/my-address',
    path: '/my-address',
    getParentRoute: () => ProtectedAccountRouteRoute,
  } as any)
const PublicSpotlightProtectedRouteRoute =
  PublicSpotlightProtectedRouteRouteImport.update({
    id: '/_protected',
    getParentRoute: () => PublicSpotlightRouteRoute,
  } as any)
const ProtectedAccountWishlistIndexRoute =
  ProtectedAccountWishlistIndexRouteImport.update({
    id: '/wishlist/',
    path: '/wishlist/',
    getParentRoute: () => ProtectedAccountRouteRoute,
  } as any)
const ProtectedAccountMyOrdersIndexRoute =
  ProtectedAccountMyOrdersIndexRouteImport.update({
    id: '/my-orders/',
    path: '/my-orders/',
    getParentRoute: () => ProtectedAccountRouteRoute,
  } as any)
const PublicSpotlightShortsIdRoute = PublicSpotlightShortsIdRouteImport.update({
  id: '/shorts/$id',
  path: '/shorts/$id',
  getParentRoute: () => PublicSpotlightRouteRoute,
} as any)
const PublicSpotlightProtectedMyPostsRoute =
  PublicSpotlightProtectedMyPostsRouteImport.update({
    id: '/my-posts',
    path: '/my-posts',
    getParentRoute: () => PublicSpotlightProtectedRouteRoute,
  } as any)
const PublicSpotlightProtectedEditProfileRoute =
  PublicSpotlightProtectedEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => PublicSpotlightProtectedRouteRoute,
  } as any)
const PublicSpotlightProtectedBookmarksRoute =
  PublicSpotlightProtectedBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => PublicSpotlightProtectedRouteRoute,
  } as any)
const PublicSpotlightProtectedAnalyticsRoute =
  PublicSpotlightProtectedAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => PublicSpotlightProtectedRouteRoute,
  } as any)
const PublicCategoriesProductsCategoryIdRoute =
  PublicCategoriesProductsCategoryIdRouteImport.update({
    id: '/categories/products/$categoryId',
    path: '/categories/products/$categoryId',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const ProtectedAccountWishlistCollectionIdRoute =
  ProtectedAccountWishlistCollectionIdRouteImport.update({
    id: '/wishlist/$collectionId',
    path: '/wishlist/$collectionId',
    getParentRoute: () => ProtectedAccountRouteRoute,
  } as any)
const ProtectedAccountMyOrdersOrderItemIdRoute =
  ProtectedAccountMyOrdersOrderItemIdRouteImport.update({
    id: '/my-orders/$orderItemId',
    path: '/my-orders/$orderItemId',
    getParentRoute: () => ProtectedAccountRouteRoute,
  } as any)
const ProtectedAccountMyOrdersReturnOrderItemIdRoute =
  ProtectedAccountMyOrdersReturnOrderItemIdRouteImport.update({
    id: '/my-orders/return/$orderItemId',
    path: '/my-orders/return/$orderItemId',
    getParentRoute: () => ProtectedAccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof ProtectedAccountRouteRouteWithChildren
  '/spotlight': typeof PublicSpotlightProtectedRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/cart': typeof PublicCartRoute
  '/search': typeof PublicSearchRoute
  '/account/my-address': typeof ProtectedAccountMyAddressRoute
  '/account/wallet': typeof ProtectedAccountWalletRoute
  '/categories/$categoryId': typeof PublicCategoriesCategoryIdRoute
  '/product/$productId': typeof PublicProductProductIdRoute
  '/spotlight/buy-clips': typeof PublicSpotlightBuyClipsRoute
  '/spotlight/campaigns': typeof PublicSpotlightCampaignsRoute
  '/account/': typeof ProtectedAccountIndexRoute
  '/categories/': typeof PublicCategoriesIndexRoute
  '/spotlight/': typeof PublicSpotlightIndexRoute
  '/account/my-orders/$orderItemId': typeof ProtectedAccountMyOrdersOrderItemIdRoute
  '/account/wishlist/$collectionId': typeof ProtectedAccountWishlistCollectionIdRoute
  '/categories/products/$categoryId': typeof PublicCategoriesProductsCategoryIdRoute
  '/spotlight/analytics': typeof PublicSpotlightProtectedAnalyticsRoute
  '/spotlight/bookmarks': typeof PublicSpotlightProtectedBookmarksRoute
  '/spotlight/edit-profile': typeof PublicSpotlightProtectedEditProfileRoute
  '/spotlight/my-posts': typeof PublicSpotlightProtectedMyPostsRoute
  '/spotlight/shorts/$id': typeof PublicSpotlightShortsIdRoute
  '/account/my-orders/': typeof ProtectedAccountMyOrdersIndexRoute
  '/account/wishlist/': typeof ProtectedAccountWishlistIndexRoute
  '/account/my-orders/return/$orderItemId': typeof ProtectedAccountMyOrdersReturnOrderItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof AuthLoginRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/cart': typeof PublicCartRoute
  '/search': typeof PublicSearchRoute
  '/spotlight': typeof PublicSpotlightIndexRoute
  '/account/my-address': typeof ProtectedAccountMyAddressRoute
  '/account/wallet': typeof ProtectedAccountWalletRoute
  '/categories/$categoryId': typeof PublicCategoriesCategoryIdRoute
  '/product/$productId': typeof PublicProductProductIdRoute
  '/spotlight/buy-clips': typeof PublicSpotlightBuyClipsRoute
  '/spotlight/campaigns': typeof PublicSpotlightCampaignsRoute
  '/account': typeof ProtectedAccountIndexRoute
  '/categories': typeof PublicCategoriesIndexRoute
  '/account/my-orders/$orderItemId': typeof ProtectedAccountMyOrdersOrderItemIdRoute
  '/account/wishlist/$collectionId': typeof ProtectedAccountWishlistCollectionIdRoute
  '/categories/products/$categoryId': typeof PublicCategoriesProductsCategoryIdRoute
  '/spotlight/analytics': typeof PublicSpotlightProtectedAnalyticsRoute
  '/spotlight/bookmarks': typeof PublicSpotlightProtectedBookmarksRoute
  '/spotlight/edit-profile': typeof PublicSpotlightProtectedEditProfileRoute
  '/spotlight/my-posts': typeof PublicSpotlightProtectedMyPostsRoute
  '/spotlight/shorts/$id': typeof PublicSpotlightShortsIdRoute
  '/account/my-orders': typeof ProtectedAccountMyOrdersIndexRoute
  '/account/wishlist': typeof ProtectedAccountWishlistIndexRoute
  '/account/my-orders/return/$orderItemId': typeof ProtectedAccountMyOrdersReturnOrderItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_protected/account': typeof ProtectedAccountRouteRouteWithChildren
  '/_public/spotlight': typeof PublicSpotlightRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/spotlight/_protected': typeof PublicSpotlightProtectedRouteRouteWithChildren
  '/_protected/account/my-address': typeof ProtectedAccountMyAddressRoute
  '/_protected/account/wallet': typeof ProtectedAccountWalletRoute
  '/_public/categories/$categoryId': typeof PublicCategoriesCategoryIdRoute
  '/_public/product/$productId': typeof PublicProductProductIdRoute
  '/_public/spotlight/buy-clips': typeof PublicSpotlightBuyClipsRoute
  '/_public/spotlight/campaigns': typeof PublicSpotlightCampaignsRoute
  '/_protected/account/': typeof ProtectedAccountIndexRoute
  '/_public/categories/': typeof PublicCategoriesIndexRoute
  '/_public/spotlight/': typeof PublicSpotlightIndexRoute
  '/_protected/account/my-orders/$orderItemId': typeof ProtectedAccountMyOrdersOrderItemIdRoute
  '/_protected/account/wishlist/$collectionId': typeof ProtectedAccountWishlistCollectionIdRoute
  '/_public/categories/products/$categoryId': typeof PublicCategoriesProductsCategoryIdRoute
  '/_public/spotlight/_protected/analytics': typeof PublicSpotlightProtectedAnalyticsRoute
  '/_public/spotlight/_protected/bookmarks': typeof PublicSpotlightProtectedBookmarksRoute
  '/_public/spotlight/_protected/edit-profile': typeof PublicSpotlightProtectedEditProfileRoute
  '/_public/spotlight/_protected/my-posts': typeof PublicSpotlightProtectedMyPostsRoute
  '/_public/spotlight/shorts/$id': typeof PublicSpotlightShortsIdRoute
  '/_protected/account/my-orders/': typeof ProtectedAccountMyOrdersIndexRoute
  '/_protected/account/wishlist/': typeof ProtectedAccountWishlistIndexRoute
  '/_protected/account/my-orders/return/$orderItemId': typeof ProtectedAccountMyOrdersReturnOrderItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/spotlight'
    | '/login'
    | '/verify-otp'
    | '/cart'
    | '/search'
    | '/account/my-address'
    | '/account/wallet'
    | '/categories/$categoryId'
    | '/product/$productId'
    | '/spotlight/buy-clips'
    | '/spotlight/campaigns'
    | '/account/'
    | '/categories/'
    | '/spotlight/'
    | '/account/my-orders/$orderItemId'
    | '/account/wishlist/$collectionId'
    | '/categories/products/$categoryId'
    | '/spotlight/analytics'
    | '/spotlight/bookmarks'
    | '/spotlight/edit-profile'
    | '/spotlight/my-posts'
    | '/spotlight/shorts/$id'
    | '/account/my-orders/'
    | '/account/wishlist/'
    | '/account/my-orders/return/$orderItemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verify-otp'
    | '/cart'
    | '/search'
    | '/spotlight'
    | '/account/my-address'
    | '/account/wallet'
    | '/categories/$categoryId'
    | '/product/$productId'
    | '/spotlight/buy-clips'
    | '/spotlight/campaigns'
    | '/account'
    | '/categories'
    | '/account/my-orders/$orderItemId'
    | '/account/wishlist/$collectionId'
    | '/categories/products/$categoryId'
    | '/spotlight/analytics'
    | '/spotlight/bookmarks'
    | '/spotlight/edit-profile'
    | '/spotlight/my-posts'
    | '/spotlight/shorts/$id'
    | '/account/my-orders'
    | '/account/wishlist'
    | '/account/my-orders/return/$orderItemId'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_protected/account'
    | '/_public/spotlight'
    | '/_auth/login'
    | '/_auth/verify-otp'
    | '/_public/cart'
    | '/_public/search'
    | '/_public/'
    | '/_public/spotlight/_protected'
    | '/_protected/account/my-address'
    | '/_protected/account/wallet'
    | '/_public/categories/$categoryId'
    | '/_public/product/$productId'
    | '/_public/spotlight/buy-clips'
    | '/_public/spotlight/campaigns'
    | '/_protected/account/'
    | '/_public/categories/'
    | '/_public/spotlight/'
    | '/_protected/account/my-orders/$orderItemId'
    | '/_protected/account/wishlist/$collectionId'
    | '/_public/categories/products/$categoryId'
    | '/_public/spotlight/_protected/analytics'
    | '/_public/spotlight/_protected/bookmarks'
    | '/_public/spotlight/_protected/edit-profile'
    | '/_public/spotlight/_protected/my-posts'
    | '/_public/spotlight/shorts/$id'
    | '/_protected/account/my-orders/'
    | '/_protected/account/wishlist/'
    | '/_protected/account/my-orders/return/$orderItemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/spotlight': {
      id: '/_public/spotlight'
      path: '/spotlight'
      fullPath: '/spotlight'
      preLoaderRoute: typeof PublicSpotlightRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/spotlight/': {
      id: '/_public/spotlight/'
      path: '/'
      fullPath: '/spotlight/'
      preLoaderRoute: typeof PublicSpotlightIndexRouteImport
      parentRoute: typeof PublicSpotlightRouteRoute
    }
    '/_public/categories/': {
      id: '/_public/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof PublicCategoriesIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof ProtectedAccountIndexRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_public/spotlight/campaigns': {
      id: '/_public/spotlight/campaigns'
      path: '/campaigns'
      fullPath: '/spotlight/campaigns'
      preLoaderRoute: typeof PublicSpotlightCampaignsRouteImport
      parentRoute: typeof PublicSpotlightRouteRoute
    }
    '/_public/spotlight/buy-clips': {
      id: '/_public/spotlight/buy-clips'
      path: '/buy-clips'
      fullPath: '/spotlight/buy-clips'
      preLoaderRoute: typeof PublicSpotlightBuyClipsRouteImport
      parentRoute: typeof PublicSpotlightRouteRoute
    }
    '/_public/product/$productId': {
      id: '/_public/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof PublicProductProductIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/categories/$categoryId': {
      id: '/_public/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof PublicCategoriesCategoryIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/account/wallet': {
      id: '/_protected/account/wallet'
      path: '/wallet'
      fullPath: '/account/wallet'
      preLoaderRoute: typeof ProtectedAccountWalletRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_protected/account/my-address': {
      id: '/_protected/account/my-address'
      path: '/my-address'
      fullPath: '/account/my-address'
      preLoaderRoute: typeof ProtectedAccountMyAddressRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_public/spotlight/_protected': {
      id: '/_public/spotlight/_protected'
      path: ''
      fullPath: '/spotlight'
      preLoaderRoute: typeof PublicSpotlightProtectedRouteRouteImport
      parentRoute: typeof PublicSpotlightRouteRoute
    }
    '/_protected/account/wishlist/': {
      id: '/_protected/account/wishlist/'
      path: '/wishlist'
      fullPath: '/account/wishlist/'
      preLoaderRoute: typeof ProtectedAccountWishlistIndexRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_protected/account/my-orders/': {
      id: '/_protected/account/my-orders/'
      path: '/my-orders'
      fullPath: '/account/my-orders/'
      preLoaderRoute: typeof ProtectedAccountMyOrdersIndexRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_public/spotlight/shorts/$id': {
      id: '/_public/spotlight/shorts/$id'
      path: '/shorts/$id'
      fullPath: '/spotlight/shorts/$id'
      preLoaderRoute: typeof PublicSpotlightShortsIdRouteImport
      parentRoute: typeof PublicSpotlightRouteRoute
    }
    '/_public/spotlight/_protected/my-posts': {
      id: '/_public/spotlight/_protected/my-posts'
      path: '/my-posts'
      fullPath: '/spotlight/my-posts'
      preLoaderRoute: typeof PublicSpotlightProtectedMyPostsRouteImport
      parentRoute: typeof PublicSpotlightProtectedRouteRoute
    }
    '/_public/spotlight/_protected/edit-profile': {
      id: '/_public/spotlight/_protected/edit-profile'
      path: '/edit-profile'
      fullPath: '/spotlight/edit-profile'
      preLoaderRoute: typeof PublicSpotlightProtectedEditProfileRouteImport
      parentRoute: typeof PublicSpotlightProtectedRouteRoute
    }
    '/_public/spotlight/_protected/bookmarks': {
      id: '/_public/spotlight/_protected/bookmarks'
      path: '/bookmarks'
      fullPath: '/spotlight/bookmarks'
      preLoaderRoute: typeof PublicSpotlightProtectedBookmarksRouteImport
      parentRoute: typeof PublicSpotlightProtectedRouteRoute
    }
    '/_public/spotlight/_protected/analytics': {
      id: '/_public/spotlight/_protected/analytics'
      path: '/analytics'
      fullPath: '/spotlight/analytics'
      preLoaderRoute: typeof PublicSpotlightProtectedAnalyticsRouteImport
      parentRoute: typeof PublicSpotlightProtectedRouteRoute
    }
    '/_public/categories/products/$categoryId': {
      id: '/_public/categories/products/$categoryId'
      path: '/categories/products/$categoryId'
      fullPath: '/categories/products/$categoryId'
      preLoaderRoute: typeof PublicCategoriesProductsCategoryIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/account/wishlist/$collectionId': {
      id: '/_protected/account/wishlist/$collectionId'
      path: '/wishlist/$collectionId'
      fullPath: '/account/wishlist/$collectionId'
      preLoaderRoute: typeof ProtectedAccountWishlistCollectionIdRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_protected/account/my-orders/$orderItemId': {
      id: '/_protected/account/my-orders/$orderItemId'
      path: '/my-orders/$orderItemId'
      fullPath: '/account/my-orders/$orderItemId'
      preLoaderRoute: typeof ProtectedAccountMyOrdersOrderItemIdRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
    '/_protected/account/my-orders/return/$orderItemId': {
      id: '/_protected/account/my-orders/return/$orderItemId'
      path: '/my-orders/return/$orderItemId'
      fullPath: '/account/my-orders/return/$orderItemId'
      preLoaderRoute: typeof ProtectedAccountMyOrdersReturnOrderItemIdRouteImport
      parentRoute: typeof ProtectedAccountRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedAccountRouteRouteChildren {
  ProtectedAccountMyAddressRoute: typeof ProtectedAccountMyAddressRoute
  ProtectedAccountWalletRoute: typeof ProtectedAccountWalletRoute
  ProtectedAccountIndexRoute: typeof ProtectedAccountIndexRoute
  ProtectedAccountMyOrdersOrderItemIdRoute: typeof ProtectedAccountMyOrdersOrderItemIdRoute
  ProtectedAccountWishlistCollectionIdRoute: typeof ProtectedAccountWishlistCollectionIdRoute
  ProtectedAccountMyOrdersIndexRoute: typeof ProtectedAccountMyOrdersIndexRoute
  ProtectedAccountWishlistIndexRoute: typeof ProtectedAccountWishlistIndexRoute
  ProtectedAccountMyOrdersReturnOrderItemIdRoute: typeof ProtectedAccountMyOrdersReturnOrderItemIdRoute
}

const ProtectedAccountRouteRouteChildren: ProtectedAccountRouteRouteChildren = {
  ProtectedAccountMyAddressRoute: ProtectedAccountMyAddressRoute,
  ProtectedAccountWalletRoute: ProtectedAccountWalletRoute,
  ProtectedAccountIndexRoute: ProtectedAccountIndexRoute,
  ProtectedAccountMyOrdersOrderItemIdRoute:
    ProtectedAccountMyOrdersOrderItemIdRoute,
  ProtectedAccountWishlistCollectionIdRoute:
    ProtectedAccountWishlistCollectionIdRoute,
  ProtectedAccountMyOrdersIndexRoute: ProtectedAccountMyOrdersIndexRoute,
  ProtectedAccountWishlistIndexRoute: ProtectedAccountWishlistIndexRoute,
  ProtectedAccountMyOrdersReturnOrderItemIdRoute:
    ProtectedAccountMyOrdersReturnOrderItemIdRoute,
}

const ProtectedAccountRouteRouteWithChildren =
  ProtectedAccountRouteRoute._addFileChildren(
    ProtectedAccountRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAccountRouteRoute: typeof ProtectedAccountRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAccountRouteRoute: ProtectedAccountRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicSpotlightProtectedRouteRouteChildren {
  PublicSpotlightProtectedAnalyticsRoute: typeof PublicSpotlightProtectedAnalyticsRoute
  PublicSpotlightProtectedBookmarksRoute: typeof PublicSpotlightProtectedBookmarksRoute
  PublicSpotlightProtectedEditProfileRoute: typeof PublicSpotlightProtectedEditProfileRoute
  PublicSpotlightProtectedMyPostsRoute: typeof PublicSpotlightProtectedMyPostsRoute
}

const PublicSpotlightProtectedRouteRouteChildren: PublicSpotlightProtectedRouteRouteChildren =
  {
    PublicSpotlightProtectedAnalyticsRoute:
      PublicSpotlightProtectedAnalyticsRoute,
    PublicSpotlightProtectedBookmarksRoute:
      PublicSpotlightProtectedBookmarksRoute,
    PublicSpotlightProtectedEditProfileRoute:
      PublicSpotlightProtectedEditProfileRoute,
    PublicSpotlightProtectedMyPostsRoute: PublicSpotlightProtectedMyPostsRoute,
  }

const PublicSpotlightProtectedRouteRouteWithChildren =
  PublicSpotlightProtectedRouteRoute._addFileChildren(
    PublicSpotlightProtectedRouteRouteChildren,
  )

interface PublicSpotlightRouteRouteChildren {
  PublicSpotlightProtectedRouteRoute: typeof PublicSpotlightProtectedRouteRouteWithChildren
  PublicSpotlightBuyClipsRoute: typeof PublicSpotlightBuyClipsRoute
  PublicSpotlightCampaignsRoute: typeof PublicSpotlightCampaignsRoute
  PublicSpotlightIndexRoute: typeof PublicSpotlightIndexRoute
  PublicSpotlightShortsIdRoute: typeof PublicSpotlightShortsIdRoute
}

const PublicSpotlightRouteRouteChildren: PublicSpotlightRouteRouteChildren = {
  PublicSpotlightProtectedRouteRoute:
    PublicSpotlightProtectedRouteRouteWithChildren,
  PublicSpotlightBuyClipsRoute: PublicSpotlightBuyClipsRoute,
  PublicSpotlightCampaignsRoute: PublicSpotlightCampaignsRoute,
  PublicSpotlightIndexRoute: PublicSpotlightIndexRoute,
  PublicSpotlightShortsIdRoute: PublicSpotlightShortsIdRoute,
}

const PublicSpotlightRouteRouteWithChildren =
  PublicSpotlightRouteRoute._addFileChildren(PublicSpotlightRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicSpotlightRouteRoute: typeof PublicSpotlightRouteRouteWithChildren
  PublicCartRoute: typeof PublicCartRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCategoriesCategoryIdRoute: typeof PublicCategoriesCategoryIdRoute
  PublicProductProductIdRoute: typeof PublicProductProductIdRoute
  PublicCategoriesIndexRoute: typeof PublicCategoriesIndexRoute
  PublicCategoriesProductsCategoryIdRoute: typeof PublicCategoriesProductsCategoryIdRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSpotlightRouteRoute: PublicSpotlightRouteRouteWithChildren,
  PublicCartRoute: PublicCartRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCategoriesCategoryIdRoute: PublicCategoriesCategoryIdRoute,
  PublicProductProductIdRoute: PublicProductProductIdRoute,
  PublicCategoriesIndexRoute: PublicCategoriesIndexRoute,
  PublicCategoriesProductsCategoryIdRoute:
    PublicCategoriesProductsCategoryIdRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
